export const FILTER_PRODUCT_NAME = 'FILTER_PRODUCT_NAME';
export const FILTER_MIN_PRICE = 'FILTER_MIN_PRICE';
export const FILTER_MAX_PRICE = 'FILTER_MAX_PRICE';
export const FILTER_PRODUCT_TYPE = 'FILTER_PRODUCT_TYPE';