export const FETCH_API_PRODUCTS_SUCCESS = 'FETCH_API_PRODUCTS_SUCCESS';
export const FETCH_API_PRODUCTS_PENDING = 'FETCH_API_PRODUCTS_PENDING';
export const FETCH_API_PRODUCTS_ERROR = 'FETCH_API_PRODUCTS_ERROR';
export const PAGINATION_CHANGE = 'PAGINATION_CHANGE';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_PRODUCTS_FILTER = 'GET_PRODUCTS_FILTER';
export const GET_PRODUCTS_TYPES = 'GET_PRODUCTS_TYPES';